---
title: "Corona ECDC Data"
author: "Peter"
date: "`r Sys.time()`"
output: html_document
fig_width: 2
fig_height: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#these libraries need to be loaded
library(utils)
library(httr)

#download the dataset from the ECDC website to a local temporary file
GET("https://opendata.ecdc.europa.eu/covid19/casedistribution/csv", authenticate(":", ":", type="ntlm"), write_disk(tf <- tempfile(fileext = ".csv")))

#read the Dataset sheet into “R”. The dataset will be called "data".
dat1 <- read.csv(tf, stringsAsFactors = FALSE)


colnames(dat1)[1] <- "Date"
colnames(dat1)[7] <- "Country"
dat1$Country[dat1$Country == "United_States_of_America"] = "USA"
dat1$Date <- as.POSIXct(as.Date(dat1$Date, "%d/%m/%Y"))

dat1 <- dat1[with(dat1, order(Country, Date)),]

case.list <- split(dat1$cases, dat1$Country)
dat1$TotalCases <- unlist(sapply(case.list, cumsum))

deaths.list <- split(dat1$deaths, dat1$Country)
dat1$TotalDeaths <- unlist(sapply(deaths.list, cumsum))


d00 <- min(dat1$Date)
dat1$d0 <- as.numeric(dat1$Date - d00)/86400


dat1$deaths.per.1e5 <- dat1$TotalDeaths / (dat1$popData2018 / 1e5)
dat1$cases.per.1e5 <- (dat1$TotalCases / dat1$popData) * 1e5
dat1$popData2018 = dat1$popData2018 / 1e6
colnames(dat1)[match("popData2018", colnames(dat1))] <- "popData2018.Mio"
dat1$letality.percent <- (dat1$TotalDeaths / dat1$TotalCases) * 100


dat1 <- subset(dat1, TotalCases > 50)

```




```{r, fig.width = 7, fig.height = 4}
library(ggplot2)

countries = c("AT", "CH", "DE", "FR", "IT", "UK", "TW", "KR", "JP", "SE", "US", "ES")
dat2 <- subset(dat1, geoId %in% countries)
options(digits = 2)
spl1 <- split(dat2, dat2$Country)
df1 <- do.call(rbind, lapply(spl1, function(i)i[nrow(i),c(2:6, 11:12, 10, 14:16)]))

df1[order(df1$TotalDeaths, decreasing = TRUE),]


plot.theme <- ggplot() + xlab("Date") + 
scale_y_log10(n.breaks = 15) +
scale_x_datetime(date_minor_breaks = "1 day") + 
theme(panel.grid.minor.y = element_blank()) +
scale_color_brewer(palette = "Paired") +
    theme(plot.title = element_text(hjust = 0.5))


plot.theme + 
geom_line(data = dat2, mapping = aes(x = Date, y = TotalCases, group = Country, colour = Country))

plot.theme +
geom_line(data = dat2,
   mapping = aes(x = Date, y = cases, group = Country, colour = Country)) +
ggtitle("New cases")

plot.theme +
geom_line(data = dat2,
   mapping = aes(x = Date, y = TotalDeaths, group = Country, colour = Country))

plot.theme +
geom_line(data = dat2,
   mapping = aes(x = Date, y = deaths, group = Country, colour = Country)) +
    ggtitle("Deaths per day")

plot.theme +
geom_line(data = dat2,
   mapping = aes(x = Date, y = deaths.per.1e5, group = Country, colour = Country)) +
    ggtitle("Deaths per 100.000")

plot.theme +
geom_line(data = dat2,
   mapping = aes(x = Date, y = cases.per.1e5, group = Country, colour = Country)) +
    ggtitle("Cases per 100.000")

plot.theme +
geom_line(data = dat2,
   mapping = aes(x = Date, y = letality.percent, group = Country, colour = Country)) +
    ggtitle("Letality in %")


library(zoo)

spl1 <- split(1:nrow(dat2), dat2$Country)

FUN1 <- function(i, logCases, days){
    c(d0 = days[i[1]], slope = coef(lm(logCases[i] ~ days[i]))[2])
}


l1 <- lapply(spl1, function(i){
    logCases <- log10(dat2$TotalCases[i])
    days <- dat2$d0[i]
    rollapply(data = seq_along(days), width = 5, FUN = FUN1, logCases, days)
})

df.slopes <- as.data.frame(do.call(rbind, l1))
colnames(df.slopes)[2] <- "slope"

df.slopes$Country <- rep(names(l1), sapply(l1, nrow))
df.slopes$Doubling.Time <- 1/(log2(10) * df.slopes$slope)
df.slopes$Date <- d00 + df.slopes$d0 * 86400
head(df.slopes)

plot.theme +  geom_line(data = df.slopes, aes(x = Date, y = Doubling.Time, group = Country, colour = Country))+
    ggtitle("Doubling Time / days")


```


